### ISSUE TITLE
Cannot read property 'offsetHeight' of undefined

### ISSUE THREAD

**Issue by ptoska** [NeXTs/Clusterize.js#121]
Cannot read property 'offsetHeight' of undefined at method getRowsHeight line 176 
`var nodes = this.content_elem.children;
      var node = nodes[Math.floor(nodes.length / 2)];
      opts.item_height = node.offsetHeight;
`

**Comment by NeXTs** [comment]
demo?

**Comment by ptoska** [comment]
That's all what i can get from windows errors on client side. I can't reproduce it or i  don't know what data has client that gives this error.

**Comment by marcgauthier** [comment]
I have the same error if I create a cluster with no items.

**Comment by ishwarrimal** [comment]
I am also facing the same issue. Our app users are getting this error so much. Following is the stack trace:

> TypeError: Cannot read property 'offsetHeight' of undefined at p.getRowsHeight (file:/app.asar/UIControllers/clusterize.min.js:11:194) at a.refresh (file:/app.asar/UIControllers/clusterize.min.js:8:505)
